[web]
web1 ansible_host=<web1-public-ip> ansible_user=azureuser ansible_ssh_private_key_file=./id_ed25519 ansible_ssh_common_args="-o StrictHostKeyChecking=no"
web2 ansible_host=<web2-public-ip> ansible_user=azureuser ansible_ssh_private_key_file=./id_ed25519 ansible_ssh_common_args="-o StrictHostKeyChecking=no"

[app]
app1 ansible_host=<app1-public-ip> ansible_user=azureuser ansible_ssh_private_key_file=./id_ed25519 ansible_ssh_common_args="-o StrictHostKeyChecking=no"

[db]
db1 ansible_host=<db1-public-ip> ansible_user=azureuser ansible_ssh_private_key_file=./id_ed25519 ansible_ssh_common_args="-o StrictHostKeyChecking=no"

[all:vars]
ansible_user=azureuser
ansible_ssh_private_key_file=./id_ed25519
